// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2bOSuV5oQgRoj_rrWDh9bzgz51XywYmg',
    appId: '1:330339934675:web:c9cad27f059db6d93b4f26',
    messagingSenderId: '330339934675',
    projectId: 'food-delivery-14139',
    authDomain: 'food-delivery-14139.firebaseapp.com',
    storageBucket: 'food-delivery-14139.firebasestorage.app',
    measurementId: 'G-QHS22QZ9PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQCHWR_RZgTZJAWkKIV3RaaYGuw0oHi8',
    appId: '1:330339934675:android:e1f80863a85a560b3b4f26',
    messagingSenderId: '330339934675',
    projectId: 'food-delivery-14139',
    storageBucket: 'food-delivery-14139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdqnHD1pOYG8qwJY0FS01rLHyPDvVvTt8',
    appId: '1:330339934675:ios:05db772ca1503dd03b4f26',
    messagingSenderId: '330339934675',
    projectId: 'food-delivery-14139',
    storageBucket: 'food-delivery-14139.firebasestorage.app',
    iosClientId: '330339934675-r2l1uep5pd4otu8p4bc8lgplnlkkbepq.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdqnHD1pOYG8qwJY0FS01rLHyPDvVvTt8',
    appId: '1:330339934675:ios:05db772ca1503dd03b4f26',
    messagingSenderId: '330339934675',
    projectId: 'food-delivery-14139',
    storageBucket: 'food-delivery-14139.firebasestorage.app',
    iosClientId: '330339934675-r2l1uep5pd4otu8p4bc8lgplnlkkbepq.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2bOSuV5oQgRoj_rrWDh9bzgz51XywYmg',
    appId: '1:330339934675:web:16f7fb5ddcb3f76f3b4f26',
    messagingSenderId: '330339934675',
    projectId: 'food-delivery-14139',
    authDomain: 'food-delivery-14139.firebaseapp.com',
    storageBucket: 'food-delivery-14139.firebasestorage.app',
    measurementId: 'G-T2S2NSQR3W',
  );
}
